services:
  postgres:
    image: postgres:17
    container_name: postgres_atividade3
    environment:
      POSTGRES_DB: atividade3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_atividade3_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atividade3"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - atividade3_net

volumes:
  postgres_atividade3_data:

networks:
  atividade3_net:
    driver: bridge